name: Semgrep Annotations

on:
  workflow_call:
    inputs:
      artifact_name:
        description: "Name of the uploaded artifact containing the Semgrep JSON output"
        required: true
        type: string
      fail_on_findings:
        description: "If true, fail the job on ERROR or WARNING findings"
        required: false
        default: false
        type: boolean

jobs:
  annotate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Download semgrep JSON
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}

      - name: Emit annotations
        id: annotate
        run: |
          ruby -r json -e '
            def level_for(severity)
              case severity
              when "ERROR" then "error"
              when "WARNING" then "warning"
              else "notice"
              end
            end

            data = JSON.parse(File.read("semgrep-output.json"))
            findings = 0

            data["results"].each do |res|
              path = res["path"]
              line = res["start"]["line"]
              level = level_for(res["extra"]["severity"])
              msg = res["extra"]["message"]
              puts "::#{level} file=#{path},line=#{line}::#{msg}"
              findings += 1 if ["error", "warning"].include?(level)
            end

            # Emit GitHub Actions output
            puts "findings=#{findings > 0}"  # for debugging
            File.open(ENV["GITHUB_OUTPUT"], "a") { |f| f.puts("has_findings=#{findings > 0}") }
          '

      - name: Fail if findings exist and fail_on_findings is true
        if: ${{ inputs.fail_on_findings == true && steps.annotate.outputs.has_findings == 'true' }}
        run: |
          echo "::error::Failing due to error or warning findings"
          exit 1
